### PR TITLE
Add the survey link.

### PR DESCRIPTION
**Pull request by arrayjam**
This sort of DOM generation is really horrible, I'm looking into
starting to use React for this sort of thing, and further interface
changes.

This at least gets the link on the page, if that doesn't pan out.

### CODE REVIEW

**Comment by kring** [comment]
Ha, perhaps we should talk.

**Comment by arrayjam** [comment]
Yep. My plan is to test it out in AREMI for any extra UI that we might require, and then figure out if it's worth lofting it out into TerriaJS.

**Comment by kring** [comment]
You're welcome to test out whatever you want, of course, but I think you'd be better served by making a small change to the explorer panel to support this sort of thing than by introducing a new UI framework into the stack.

**Comment by meh9** [comment]
Looks good to me!

**Pull request merged**
