### PR TITLE
Replace dataSetID (deprecated in TerriaJS 2.0.0) with datasetId

### PR DESCRIPTION
**Pull request by RacingTadpole**
Only merge this once we're using Terria 2.0.0.

### CODE REVIEW

**Comment by meh9** [comment]
So, this isn't actually a problem for us at the moment, because these end up in `nm.json` which we don't use so it's probably not a big deal to merge this.

However, we do have our own inclusion of the ABS services that we do need to change when this happens, so all of the mentions of `dataSetID` in this search must be fixed:

https://github.com/NICTA/aremi-natmap/search?utf8=%E2%9C%93&q=dataSetID

**Comment by RacingTadpole** [comment]
Thanks Mats. Actually this PR does change both the `nm.json` source and the `aremi.json` source, right? Although from your search I see I missed the reference in `wwwroot/init/abs.json`.  I'll push through an update for that.

**Comment by meh9** [comment]
Argh, I need to learn to scroll down to the bottom, sorry to have accused you of not completing the entire job!

**Comment by RacingTadpole** [comment]
I've simply deleted the old `wwwroot/init/abs.json`. It doesn't seem to add anything useful, since the ABS items are already in the catalog.

**Pull request merged**
