### PR TITLE
Make the colour of the new progress bar the special AREMI Turquoise shade

### PR DESCRIPTION
**Pull request by meh9**

### CODE REVIEW

**Comment by kring** [comment]
Should this color be the default in TerriaJS?  Certainly it's better on white basemaps.

**Comment by AlexGilleran** [comment]
It's worth considering - I imagine it's harder to see when it covers the ocean though. When I was testing I had it set to bright red :).

**Comment by meh9** [comment]
Get your own colour! ;)

Yes, I think the white was hard to see, but you guys usually use different maps than us.

**Comment by kring** [comment]
NM uses Bing Aerial, but other maps use Positron by default, so it might be good to have a better default (even if we don't steal our color).  There's some value in subtlety, though.  It has the potential to be distracting.

**Comment by AlexGilleran** [comment]
Cricket faced a similar problem picking a ball colour that could be seen against everything and...

pink cricket ball

:laughing:

**Pull request merged**
