### PR TITLE
Added "Contribute Data" link to sidebar.

### PR DESCRIPTION
**Pull request by AlexGilleran**
Looks like this:

image

Opens the google form in a new window.

### CODE REVIEW

**Comment by axman6** [comment]
Not sure what @meh9 or Cam think, but I'd prefer to see it below the feedback text, but I can't think of a compelling argument for why it should be that way =)

**Comment by AlexGilleran** [comment]
That'd work too I guess? Will make it so unless @meh9 or @cam-grant have a dissenting opinion?

**Comment by cam-grant** [comment]
That's fine for the time being - the idea is to move this kind of stuff to the welcome tab in the new UI.

**Comment by AlexGilleran** [comment]
Moved.

image

**Pull request merged**
